In [1]:
# Consider the below code to answer further questions:
# import numpy as np
# list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]
# array_list = np.array(object = list_)

In [2]:
# Q1. Is there any difference in the data type of variables list_ and array_list? If there is then 
#     write a code to print the data types of both the variables.

In [3]:
import numpy as np
list_ = [ '1' , '2', '3', '4', '5' ]
array_list = np.array(object = list_)

In [4]:
list_

['1', '2', '3', '4', '5']

In [5]:
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [6]:
#           Yes, both are different to each other because the data type of first variable (list_) is list and the 
#   data type of second variable (array_list) is 1D array because we have put the variable 'list_' inside the 
#   np.array() which have changed into array.


In [7]:
type(list_)

list

In [8]:
array_list.dtype

dtype('<U1')

In [9]:
# Note :- U1 means-  8-bit unsigned integer

In [10]:
# Q2. Write a code to print the data type of each and every element of both the variables list_ and
# arra_list.

In [11]:
# Ans- 
# for list_ 
for i in  list_:
    print("element : {} and it's data type : {}".format(i, type(i)))

element : 1 and it's data type : <class 'str'>
element : 2 and it's data type : <class 'str'>
element : 3 and it's data type : <class 'str'>
element : 4 and it's data type : <class 'str'>
element : 5 and it's data type : <class 'str'>


In [12]:
# for array_list
for i in array_list:
        print("element : {} and it's data type : {}".format(i, i.dtype))

element : 1 and it's data type : <U1
element : 2 and it's data type : <U1
element : 3 and it's data type : <U1
element : 4 and it's data type : <U1
element : 5 and it's data type : <U1


In [13]:
type(array_list)

numpy.ndarray

In [14]:
# Q3. Considering the following changes in the variable, array_list:
    # array_list = np.array(object = list_, dtype = int)

    # Will there be any difference in the data type of the elements present in both the variables, list_ and
    # arra_list? If so then print the data types of each and every element present in both the variables, list_
    # and arra_list.

In [15]:
# Ans-
arra_list = np.array(object = list_, dtype = int)

In [16]:
arra_list

array([1, 2, 3, 4, 5])

In [17]:
for i in list_:
    print("element : {} and it's data type : {}".format(i, type(i)))

element : 1 and it's data type : <class 'str'>
element : 2 and it's data type : <class 'str'>
element : 3 and it's data type : <class 'str'>
element : 4 and it's data type : <class 'str'>
element : 5 and it's data type : <class 'str'>


In [18]:
for i in arra_list:
    print("element : {} and it's data type : {}".format(i, i.dtype))

element : 1 and it's data type : int64
element : 2 and it's data type : int64
element : 3 and it's data type : int64
element : 4 and it's data type : int64
element : 5 and it's data type : int64


In [5]:
# Consider the below code to answer further questions:
# import numpy as np
# num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
# num_array = np.array(object = num_list)

In [20]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [21]:
# Q4. Write a code to find the following characteristics of variable, num_array:
# (i) shape
# (ii) size

In [32]:
np.shape(num_array)

(2, 3)

In [33]:
np.size(num_array)

6

In [7]:
# Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
# creation function.
# [Hint: The size of the array will be 9 and the shape will be (3,3).]

In [34]:
# Ans- 
zero_array = np.zeros((3,3))

In [35]:
zero_array

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [38]:
# Q6. Create an identity matrix of shape (5,5) using numpy functions?
# [Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [48]:
# Ans- 
identity_array = np.eye(5,5)

In [47]:
idetity_array

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])